### ISSUE TITLE
GetDomainSid.cs should have domain

### ISSUE THREAD

**Issue by ymgh96** [FortyNorthSecurity/EDD#10]
Hi, This is a simple problem.
You said in readme, the GetDomainSid function by default takes current domain if no domain is provided. But we should specify domain name for using. I also check in code, it checks providing domain really.

**Comment by ChrisTruncer** [comment]
It already does this. You can specify a domain name to use, or don't specify anything, and then it uses the current domain

**Comment by ymgh96** [comment]
🙄🤔
I put my output in bellow code block! It shows that enter domain name is not optional!
```
EDD.exe -f GetDomainSid

[X] Failure to enumerate info - EDD.Models.EDDException: DomainName cannot be empty
   at EDD.Functions.GetDomainSid.Execute(ParsedArgs args)

[!] EDD is done running!
```
Also according to its code it is obvious.
https://github.com/FortyNorthSecurity/EDD/blob/96e8564415d311d02821a302d2100e7da67c3125/EDD/Functions/GetDomainSid.cs#L18
