### ISSUE TITLE
GetSidData just work for users

### ISSUE THREAD

**Issue by ymgh96** [FortyNorthSecurity/EDD#11]
You said in readme the GetSidData function return domain, group and users name from sid (GetSidData exists in both Forest/Domain Information and User Information). but it just work fine for user's sid. And for domain return error meesage.

**Comment by ChrisTruncer** [comment]
There already is a function for getting the domain sid and the sid of a group. This is for a user.

**Comment by ymgh96** [comment]
#13 
According to your answer readme should be edited.
