### ISSUE TITLE
wrong implementation in GetDomainGroupSid.cs

### ISSUE THREAD

**Issue by ymgh96** [FortyNorthSecurity/EDD#12]
Hello,
You get DomainName parameter in line 22 for "GetDomainGroupSID" function. But I think it is wrong!
https://github.com/FortyNorthSecurity/EDD/blob/82aa4da15adb29ea5f8a6bdb6833bf31ff5e54db/EDD/Functions/GetDomainGroupSid.cs#L22 According to the GetDomainGroupSID function definition this function expects GroupName not DomainName!
https://github.com/FortyNorthSecurity/EDD/blob/82aa4da15adb29ea5f8a6bdb6833bf31ff5e54db/EDD/Amass.cs#L79 As a result function return "Could not find domain group" error always!

**Comment by ChrisTruncer** [comment]
Yup, you're right. Need to get this fixed

**Comment by ChrisTruncer** [comment]
The fix is now pushed, thanks again for posting this
